export const GOOGLE_SIGN_IN_START = "GOOGLE_SIGN_IN_START";
export const GOOGLE_SIGN_IN_SUCCESS = "GOOGLE_SIGN_IN_SUCCESS";
export const GOOGLE_SIGN_IN_FAILURE = "GOOGLE_SIGN_IN_FAILURE";

export const GOOGLE_SIGN_OUT_START = "GOOGLE_SIGN_OUT_START";
export const GOOGLE_SIGN_OUT_SUCCESS = "GOOGLE_SIGN_OUT_SUCCESS";
export const GOOGLE_SIGN_OUT_FAILURE = "GOOGLE_SIGN_OUT_FAILURE";
