export const SHOW_BLOG_POST = "SHOW_BLOG_POST"
export const UPDATE_LIKES_SUCCESS = "UPDATE_LIKES_SUCCESS"

export const CREATE_POST = "CREATE_POST"

export const FETCH_POST_LOADING = "FETCH_POST_LOADING"
export const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS"
export const FETCH_POST_FAILURE = "FETCH_POST_FAILURE"

export const UPDATE_POST = " UPDATE_POST"
export const DELETE_POST = "DELETE_POST"